title: Al-Hassan Badamasi
logo: Al2.jpg
description: I’m a data analyst with a strong foundation in transforming complex datasets into actionable insights, backed by two years of experience across industries. My expertise lies in using Excel, SQL, and Power BI to uncover patterns, build interactive dashboards, and support data-driven decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
